# 是否记录发出的信息
logSend: false
# 是否记录收到的信息
logReceive: false

# 消息中心地址
serviceHost: "localhost"
# 消息中心端口
servicePort: 8123

# 服务器名称
# 请与bc中保持一致，在一些关键代码中将会被使用到
# （例如：将玩家传送至某个服务器时，取的就是这个服务器名字）
# "ServiceCentre" 为服务中心保留名称，请不要使用
name: "BungeeCord1"

# 服务器别名
# 仅作为展示用
nickName: "BC1"

# 服务组线程，一般设置为2~3即可
nioThread: 2
