name: HamsterService-Spigot
version: ${project.version}
main: cn.hamster3.service.spigot.HamsterServicePlugin
load: STARTUP
author: Hamster3
website: ${project.url}
description: ${project.description}
